// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxlklgnfskkdwqzveuhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4bGtsZ25mc2trZHdxenZldWhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MDI1NDgsImV4cCI6MjA2ODI3ODU0OH0.wEvE_8PrCZaisjeLKDFgL1zhHdKbN9FZwBkGYgvdYzE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});